name: Job - Lint check (Go)

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.mod
      - name: Install golangci-lint
        run: curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v2.12.2
      - name: Run linter
        run: golangci-lint run
      - name: Run Formatter
        run: golangci-lint fmt
      - id: check-format
        name: Check code formatted
        run: |
          if git diff --name-only | grep -q .; then
            echo "formatted=true" >> $GITHUB_OUTPUT
          else
            echo "formatted=false" >> $GITHUB_OUTPUT
          fi
      - if: steps.check-format.outputs.formatted == 'true'
        name: Commit formatted code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m ":art: Apply format"
          git push
